version: '3.3'

# This file expects some .env file (within same dir) defining the following vars:
# 	DOMAIN_NAME
# 	DOMAIN_CONTACT
# 	MYSQL_ROOT_PASSWORD
# 	MYSQL_DATABASE
# 	MYSQL_USER
# 	MYSQL_PASSWORD


# We define all services and dependencies under the 'services' section, so that all related containers run within the same stack
services:
   {db_ID}:
     container_name: sql.${DOMAIN_NAME}
     image: mysql:5.7
     # allow packets up to 512 MB (for imports)
     # commented - should be included in the `mysql.cnf` below
     # command: --max_allowed_packet=536870912
     volumes:
       - db_data:/var/lib/mysql
       - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf      
     restart: always
     networks:
       - proxynet
     environment:
       - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
       - MYSQL_DATABASE=${MYSQL_DATABASE}
       - MYSQL_USER=${MYSQL_USER}
       - MYSQL_PASSWORD=${MYSQL_PASSWORD}
   phpmyadmin:
     container_name: phpmyadmin.${DOMAIN_NAME}
     image: phpmyadmin/phpmyadmin
     depends_on:
       - {db_ID}     
     links:
       - {db_ID}:db
     networks:
       - proxynet
     environment:
       # Login page requires HTTPS, so we must redirect even if no valid certificate is set
       #- HTTPS_METHOD=noredirect
       - VIRTUAL_PORT=80
       - VIRTUAL_HOST=phpmyadmin.${DOMAIN_NAME}
       - UPLOAD_LIMIT=100M
       - MAX_EXECUTION_TIME=3600
       - MEMORY_LIMIT=128M
       - PMA_HOST={db_ID}
   equal_srv:
     image: equalframework/equal:latest
     container_name: ${DOMAIN_NAME}
     links:
       - {db_ID}:db
     depends_on:
       - {db_ID}  
     restart: always
     volumes:
       - /home/${DOMAIN_NAME}/www:/var/www/html
       # Map local file for custom PHP config (e.g. upload_max_filesize)
       - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
     extra_hosts:
       # If instance calls itself through HTTP, force sending the requests to the reverse proxy 
       - "${DOMAIN_NAME}:${EXTERNAL_IP_ADDRESS}"
     networks:
       - proxynet
     environment:
       - EQ_CIPHER_KEY=xxxxxxxxxxxxxx
       - EQ_DB_NAME=${MYSQL_DATABASE}
       - EQ_DB_HOST={db_ID}
       - EQ_DB_PORT=3306
       - EQ_DB_USER=${MYSQL_USER}
       - EQ_DB_PASSWORD=${MYSQL_PASSWORD}
       # Remember to disable noredirect once the SSL certificate has been set up
       - HTTPS_METHOD=noredirect
       - VIRTUAL_PORT=80
       # Add domains that require a SSL cert [comma separated] (necessary for direct HTTPS connection)
       - VIRTUAL_HOST=${DOMAIN_NAME}
       - LETSENCRYPT_HOST=${DOMAIN_NAME}
       - LETSENCRYPT_EMAIL=${DOMAIN_CONTACT}

# To expose the services, we use the 'proxynet' which contains a nginx reverse proxy.
# Only services having a VIRTUAL_HOST environment variable set will be accessible.
networks:
  proxynet:
    external: true
volumes:
  db_data:
