openapi: 3.0.0
info:
  title: B2 Host API
  description: API for managing the b2 host and its instances.
  version: 1.0.0
paths:
  /status:
    post:
      summary: Get the status of the b2 host.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Status retrieved successfully.
        '500':
          description: Internal server error.

  /ip:
    post:
      summary: Set the public interface IP address.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - ip_address
                - subnet
              properties:
                ip_address:
                  type: string
                  format: ipv4
                  example: "192.168.1.15"
                subnet:
                  type: string
                  example: "24"
      responses:
        '200':
          description: IP address set successfully.
        '400':
          description: Invalid input.
        '500':
          description: Internal server error.

  /reboot:
    post:
      summary: Reboot the b2 host.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: {}
      responses:
        '200':
          description: Host rebooted successfully.
        '500':
          description: Internal server error.

  /instances:
    post:
      summary: Get the list of instances on the b2 host.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                with_deleted:
                  type: boolean
                  default: false
      responses:
        '200':
          description: List of instances retrieved successfully.
        '500':
          description: Internal server error.

  /instance/create:
    post:
      summary: Create a new instance.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - USERNAME
                - APP_USERNAME
                - APP_PASSWORD
              properties:
                USERNAME:
                  type: string
                  example: "equal.local"
                APP_USERNAME:
                  type: string
                  example: "root"
                APP_PASSWORD:
                  type: string
                  example: "thepassword1234"
                symbiose:
                  type: boolean
                  default: false
                equalpress:
                  type: boolean
                  default: false
                CIPHER_KEY:
                  type: string
                  example: "32-character-random-key"
                HTTPS_REDIRECT:
                  type: string
                  enum: [redirect, noredirect]
                  default: "noredirect"
                WP_VERSION:
                  type: string
                  default: "6.4"
                WP_EMAIL:
                  type: string
                  default: "root@equal.local"
                WP_TITLE:
                  type: string
                  default: "eQualPress"
                MEM_LIMIT:
                  type: string
                  default: "1000M"
      responses:
        '201':
          description: Instance created successfully.
        '400':
          description: Invalid input.
        '500':
          description: Internal server error.

  /instance/delete:
    post:
      summary: Delete an existing instance.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - instance
              properties:
                instance:
                  type: string
                  example: "equal.local"
      responses:
        '200':
          description: Instance deleted successfully.
        '400':
          description: Invalid input.
        '500':
          description: Internal server error.

  /instance/status:
    post:
      summary: Get the status of an instance.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - instance
              properties:
                instance:
                  type: string
                  example: "equal.local"
      responses:
        '200':
          description: Instance status retrieved successfully.
        '500':
          description: Internal server error.

  /instance/backup:
    post:
      summary: Create a backup of an instance.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - instance
              properties:
                instance:
                  type: string
                  example: "equal.local"
                encrypt:
                  type: boolean
                  default: true
      responses:
        '200':
          description: Backup created successfully.
        '400':
          description: Invalid input.
        '500':
          description: Internal server error.

  /instance/export-backup:
    post:
      summary: Export the backup of an instance to the configured backup host.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - instance
                - backup_id
              properties:
                instance:
                  type: string
                  example: "equal.local"
                backup_id:
                  type: string
                  example: "20241210091621"
      responses:
        '200':
          description: Backup exported successfully.
        '500':
          description: Internal server error.

  /instance/import-backup:
    post:
      summary: Import a backup from the configured backup host.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - instance
                - backup_id
              properties:
                instance:
                  type: string
                  example: "equal.local"
                backup_id:
                  type: string
                  example: "20241210091621"
      responses:
        '200':
          description: Backup imported successfully.
        '500':
          description: Internal server error.

  /instance/backups:
    post:
      summary: Get the list of backups for an instance.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - instance
              properties:
                instance:
                  type: string
                  example: "equal.local"
      responses:
        '200':
          description: List of backups retrieved successfully.
        '500':
          description: Internal server error.

  /instance/restore:
    post:
      summary: Restore an instance's state from a backup.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - instance
                - backup_id
                - passphrase
              properties:
                instance:
                  type: string
                  example: "equal.local"
                backup_id:
                  type: string
                  example: "20241210091621"
                passphrase:
                  type: string
                  example: "thepassword1234"
      responses:
        '200':
          description: Instance restored successfully.
        '500':
          description: Internal server error.

  /instance/enable-maintenance:
    post:
      summary: Enable maintenance mode for an instance.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - instance
              properties:
                instance:
                  type: string
                  example: "equal.local"
      responses:
        '200':
          description: Maintenance mode enabled successfully.
        '500':
          description: Internal server error.

  /instance/disable-maintenance:
    post:
      summary: Disable maintenance mode for an instance.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - instance
              properties:
                instance:
                  type: string
                  example: "equal.local"
      responses:
        '200':
          description: Maintenance mode disabled successfully.
        '500':
          description: Internal server error.
