version: "3"
services:
  equal_srv:
    image: equalframework/equal
    container_name: ${USERNAME}
    restart: always
    ports:
      - "{{EQ_PORT}}:80"
    volumes:
      - ./www/.:/var/www/html
    extra_hosts:
      - "${USERNAME}:127.0.0.1"
    hostname: ${USERNAME}
    domainname: local
    environment:
      - EQ_DB_HOST={{DB_HOSTNAME}}
      - EQ_DB_USER=${APP_USERNAME}
      - EQ_DB_PASS=${APP_PASSWORD}
      - EQ_DB_NAME=equal
      - EQ_CIPHER_KEY=${CIPHER_KEY}
      - HTTPS_METHOD=${HTTPS_REDIRECT}
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=${USERNAME}
      - LETSENCRYPT_HOST=${USERNAME}
      - LETSENCRYPT_EMAIL=contact@${USERNAME}
    links:
      - "mysql"
    networks:
      - proxynet
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    container_name: {{DB_HOSTNAME}}
    restart: always
    ports:
      - "{{DB_PORT}}:3306"
    environment:
      - MYSQL_DATABASE=equal
      - MYSQL_ROOT_PASSWORD=${APP_PASSWORD}
    networks:
      - proxynet
    volumes:
      - db_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: {{PMA_HOSTNAME}}
    restart: always
    ports:
      - "{{PMA_PORT}}:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST={{DB_HOSTNAME}}
      - PMA_USER=${APP_USERNAME}
      - PMA_PASSWORD=${APP_PASSWORD}
      - HTTPS_METHOD=${HTTPS_REDIRECT}
      - VIRTUAL_PORT=80
      - VIRTUAL_HOST=phpmyadmin.${USERNAME}
      - UPLOAD_LIMIT=100M
      - MAX_EXECUTION_TIME=3600
      - MEMORY_LIMIT=128M
    links:
      - "mysql"
    networks:
      - proxynet
    depends_on:
      - mysql
networks:
  proxynet:
    external: true
volumes:
  db_data:
